image:
- Visual Studio 2019
- macOS
- Ubuntu

skip_branch_with_pr: true
stack: python 3.10

environment:
  GITHUB_TOKEN:
    secure: 7sOlr0sdn+ttszef9sj9sl8T6Yn+2mS+Bj2yYuEuGAt4ihqrydk1mlDR0q8+XgD1

install:
#- python -m pip install --upgrade pip virtualenv
- python.exe -m pip install --upgrade pip setuptools wheel
- pip install pillow
- pip install pyinstaller
- pip install -r requirements.txt

build_script:
- flet pack main.py --name "Python Desktop Notifications" --icon test_images/png_test_image.png --product-name "Python Desktop Notifications" --product-version "0.1" --copyright "Copyright (c) 2023 TheEthicalBoy"

test: off

# Publish artifacts to GitHub Releases on "tag" builds
deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  on:
    APPVEYOR_REPO_TAG: true

#
#   Windows package
#
for:
-
  matrix:
    only:
    - image: Visual Studio 2019

  after_build:
  - 7z a python-desktop-notications-windows.zip %CD%\dist\*.exe

  artifacts:
  - path: python-desktop-notications-windows.zip

#
#   macOS package
#
-
  matrix:
    only:
    - image: macOS

  after_build:
  - tar -czvf python-desktop-notications-macos.tar.gz -C dist python-desktop-notications.app

  artifacts:
  - path: python-desktop-notications-macos.tar.gz

#
#   Linux package
#
-
  matrix:
    only:
    - image: Ubuntu

  after_build:
  - tar -czvf python-desktop-notications-linux.tar.gz -C dist python-desktop-notications

  artifacts:
  - path: python-desktop-notications-linux.tar.gz
